### ISSUE TITLE
X13 failing to migrate custom module classes

### ISSUE THREAD

**Issue by ChristopherBass** [Kentico/xperience-migration-toolkit#172]
### Brief bug description

I have a custom module in Kentico 13 , and when I did the migrate, the custom module itself is generated but its classes are not.

### Repro steps

1. run dotnet migrate --sites --custom-modules
2. Look for custom modules in code

### Expected behavior

Custom modules should add the module classes.

### Test environment

 - Visual Studio 2022 on a X13.0.133 site going to a XbyK 28.4.1 site

### Additional context

MigrateCustomModulesCommand.MigrateClasses line 54 selects "Custom module classes" where ClassIsForm = 1 - but for custom modules in Kentico 13, ClassIsForm = 0. Instead, this method ends up selecting things like BizForms instead.

**Comment by liparova** [comment]
Thank you for reporting the issue. Our team will investigate it thoroughly and provide updates on the resolution.
