### ISSUE TITLE
Custom modules

### ISSUE THREAD

**Issue by DavidSlavik** [Kentico/xperience-migration-toolkit#82]
We know that UI components are different in KX13 and XbK but I would like to help our customers to migrate as much as possible from the previous solution. I believe that class definitions and it's data might be possible to migrate even though we separated the solution between class fields definition and UI forms.

**Comment by DavidSlavik** [comment]
TBD after synchro meeting.

**Comment by DavidBKentico** [comment]
Just a quick reminder that this should also open up the option to migrate custom fields for customizable system classes, Mostly relevant for Contacts and maybe Users.
